// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ConversationsApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum PlatformConnectionState: Int, CaseIterable {
  case unknown = 0
  case connecting = 1
  case connected = 2
  case disconnected = 3
  case denied = 4
  case error = 5
  case fatalError = 6
}

enum PlatformSyncStatus: Int, CaseIterable {
  case started = 0
  case conversationsListCompleted = 1
  case completed = 2
  case failed = 3
}

enum PlatformLogLevel: Int, CaseIterable {
  case silent = 0
  case fatal = 1
  case error = 2
  case warning = 3
  case info = 4
  case debug = 5
  case trace = 6
}

enum PlatformConversationStatus: Int, CaseIterable {
  case joined = 0
  case notParticipating = 1
}

enum PlatformMediaCategory: Int, CaseIterable {
  case media = 0
  case body = 1
  case history = 2
}

enum PlatformPushTokenType: Int, CaseIterable {
  case apns = 0
  case fcm = 1
}

enum PlatformTokenEventType: Int, CaseIterable {
  case aboutToExpire = 0
  case expired = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientData: Hashable, CustomStringConvertible {
  var myIdentity: String
  var connectionState: PlatformConnectionState
  var syncStatus: PlatformSyncStatus? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientData? {
    let myIdentity = pigeonVar_list[0] as! String
    let connectionState = pigeonVar_list[1] as! PlatformConnectionState
    let syncStatus: PlatformSyncStatus? = nilOrValue(pigeonVar_list[2])

    return ClientData(
      myIdentity: myIdentity,
      connectionState: connectionState,
      syncStatus: syncStatus
    )
  }
  func toList() -> [Any?] {
    return [
      myIdentity,
      connectionState,
      syncStatus,
    ]
  }
  static func == (lhs: ClientData, rhs: ClientData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.myIdentity, rhs.myIdentity) && ConversationsApiPigeonInternal.deepEquals(lhs.connectionState, rhs.connectionState) && ConversationsApiPigeonInternal.deepEquals(lhs.syncStatus, rhs.syncStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientData")
    ConversationsApiPigeonInternal.deepHash(value: myIdentity, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: connectionState, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: syncStatus, hasher: &hasher)
  }

  public var description: String {
    return "ClientData(myIdentity: \(String(describing: myIdentity)), connectionState: \(String(describing: connectionState)), syncStatus: \(String(describing: syncStatus)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConversationData: Hashable, CustomStringConvertible {
  var sid: String
  var status: PlatformConversationStatus
  var uniqueName: String? = nil
  var friendlyName: String? = nil
  var attributesJson: String? = nil
  var lastMessageIndex: Int64? = nil
  var lastMessageDateMillis: Int64? = nil
  var lastReadMessageIndex: Int64? = nil
  var dateCreatedMillis: Int64? = nil
  var createdBy: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConversationData? {
    let sid = pigeonVar_list[0] as! String
    let status = pigeonVar_list[1] as! PlatformConversationStatus
    let uniqueName: String? = nilOrValue(pigeonVar_list[2])
    let friendlyName: String? = nilOrValue(pigeonVar_list[3])
    let attributesJson: String? = nilOrValue(pigeonVar_list[4])
    let lastMessageIndex: Int64? = nilOrValue(pigeonVar_list[5])
    let lastMessageDateMillis: Int64? = nilOrValue(pigeonVar_list[6])
    let lastReadMessageIndex: Int64? = nilOrValue(pigeonVar_list[7])
    let dateCreatedMillis: Int64? = nilOrValue(pigeonVar_list[8])
    let createdBy: String? = nilOrValue(pigeonVar_list[9])

    return ConversationData(
      sid: sid,
      status: status,
      uniqueName: uniqueName,
      friendlyName: friendlyName,
      attributesJson: attributesJson,
      lastMessageIndex: lastMessageIndex,
      lastMessageDateMillis: lastMessageDateMillis,
      lastReadMessageIndex: lastReadMessageIndex,
      dateCreatedMillis: dateCreatedMillis,
      createdBy: createdBy
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      status,
      uniqueName,
      friendlyName,
      attributesJson,
      lastMessageIndex,
      lastMessageDateMillis,
      lastReadMessageIndex,
      dateCreatedMillis,
      createdBy,
    ]
  }
  static func == (lhs: ConversationData, rhs: ConversationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsApiPigeonInternal.deepEquals(lhs.status, rhs.status) && ConversationsApiPigeonInternal.deepEquals(lhs.uniqueName, rhs.uniqueName) && ConversationsApiPigeonInternal.deepEquals(lhs.friendlyName, rhs.friendlyName) && ConversationsApiPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson) && ConversationsApiPigeonInternal.deepEquals(lhs.lastMessageIndex, rhs.lastMessageIndex) && ConversationsApiPigeonInternal.deepEquals(lhs.lastMessageDateMillis, rhs.lastMessageDateMillis) && ConversationsApiPigeonInternal.deepEquals(lhs.lastReadMessageIndex, rhs.lastReadMessageIndex) && ConversationsApiPigeonInternal.deepEquals(lhs.dateCreatedMillis, rhs.dateCreatedMillis) && ConversationsApiPigeonInternal.deepEquals(lhs.createdBy, rhs.createdBy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConversationData")
    ConversationsApiPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: status, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: uniqueName, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: friendlyName, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: lastMessageIndex, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: lastMessageDateMillis, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: lastReadMessageIndex, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: dateCreatedMillis, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: createdBy, hasher: &hasher)
  }

  public var description: String {
    return "ConversationData(sid: \(String(describing: sid)), status: \(String(describing: status)), uniqueName: \(String(describing: uniqueName)), friendlyName: \(String(describing: friendlyName)), attributesJson: \(String(describing: attributesJson)), lastMessageIndex: \(String(describing: lastMessageIndex)), lastMessageDateMillis: \(String(describing: lastMessageDateMillis)), lastReadMessageIndex: \(String(describing: lastReadMessageIndex)), dateCreatedMillis: \(String(describing: dateCreatedMillis)), createdBy: \(String(describing: createdBy)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaData: Hashable, CustomStringConvertible {
  var sid: String
  var category: PlatformMediaCategory
  var contentType: String
  var size: Int64
  var filename: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaData? {
    let sid = pigeonVar_list[0] as! String
    let category = pigeonVar_list[1] as! PlatformMediaCategory
    let contentType = pigeonVar_list[2] as! String
    let size = pigeonVar_list[3] as! Int64
    let filename: String? = nilOrValue(pigeonVar_list[4])

    return MediaData(
      sid: sid,
      category: category,
      contentType: contentType,
      size: size,
      filename: filename
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      category,
      contentType,
      size,
      filename,
    ]
  }
  static func == (lhs: MediaData, rhs: MediaData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsApiPigeonInternal.deepEquals(lhs.category, rhs.category) && ConversationsApiPigeonInternal.deepEquals(lhs.contentType, rhs.contentType) && ConversationsApiPigeonInternal.deepEquals(lhs.size, rhs.size) && ConversationsApiPigeonInternal.deepEquals(lhs.filename, rhs.filename)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaData")
    ConversationsApiPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: category, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: contentType, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: size, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: filename, hasher: &hasher)
  }

  public var description: String {
    return "MediaData(sid: \(String(describing: sid)), category: \(String(describing: category)), contentType: \(String(describing: contentType)), size: \(String(describing: size)), filename: \(String(describing: filename)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageData: Hashable, CustomStringConvertible {
  var conversationSid: String
  var sid: String
  var index: Int64
  var media: [MediaData]
  var author: String? = nil
  var body: String? = nil
  var dateCreatedMillis: Int64? = nil
  var attributesJson: String? = nil
  var participantSid: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageData? {
    let conversationSid = pigeonVar_list[0] as! String
    let sid = pigeonVar_list[1] as! String
    let index = pigeonVar_list[2] as! Int64
    let media = pigeonVar_list[3] as! [MediaData]
    let author: String? = nilOrValue(pigeonVar_list[4])
    let body: String? = nilOrValue(pigeonVar_list[5])
    let dateCreatedMillis: Int64? = nilOrValue(pigeonVar_list[6])
    let attributesJson: String? = nilOrValue(pigeonVar_list[7])
    let participantSid: String? = nilOrValue(pigeonVar_list[8])

    return MessageData(
      conversationSid: conversationSid,
      sid: sid,
      index: index,
      media: media,
      author: author,
      body: body,
      dateCreatedMillis: dateCreatedMillis,
      attributesJson: attributesJson,
      participantSid: participantSid
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      sid,
      index,
      media,
      author,
      body,
      dateCreatedMillis,
      attributesJson,
      participantSid,
    ]
  }
  static func == (lhs: MessageData, rhs: MessageData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsApiPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsApiPigeonInternal.deepEquals(lhs.index, rhs.index) && ConversationsApiPigeonInternal.deepEquals(lhs.media, rhs.media) && ConversationsApiPigeonInternal.deepEquals(lhs.author, rhs.author) && ConversationsApiPigeonInternal.deepEquals(lhs.body, rhs.body) && ConversationsApiPigeonInternal.deepEquals(lhs.dateCreatedMillis, rhs.dateCreatedMillis) && ConversationsApiPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson) && ConversationsApiPigeonInternal.deepEquals(lhs.participantSid, rhs.participantSid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MessageData")
    ConversationsApiPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: index, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: media, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: author, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: body, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: dateCreatedMillis, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: participantSid, hasher: &hasher)
  }

  public var description: String {
    return "MessageData(conversationSid: \(String(describing: conversationSid)), sid: \(String(describing: sid)), index: \(String(describing: index)), media: \(String(describing: media)), author: \(String(describing: author)), body: \(String(describing: body)), dateCreatedMillis: \(String(describing: dateCreatedMillis)), attributesJson: \(String(describing: attributesJson)), participantSid: \(String(describing: participantSid)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ParticipantData: Hashable, CustomStringConvertible {
  var sid: String
  var identity: String? = nil
  var dateCreatedMillis: Int64? = nil
  var lastReadMessageIndex: Int64? = nil
  var attributesJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ParticipantData? {
    let sid = pigeonVar_list[0] as! String
    let identity: String? = nilOrValue(pigeonVar_list[1])
    let dateCreatedMillis: Int64? = nilOrValue(pigeonVar_list[2])
    let lastReadMessageIndex: Int64? = nilOrValue(pigeonVar_list[3])
    let attributesJson: String? = nilOrValue(pigeonVar_list[4])

    return ParticipantData(
      sid: sid,
      identity: identity,
      dateCreatedMillis: dateCreatedMillis,
      lastReadMessageIndex: lastReadMessageIndex,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      identity,
      dateCreatedMillis,
      lastReadMessageIndex,
      attributesJson,
    ]
  }
  static func == (lhs: ParticipantData, rhs: ParticipantData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsApiPigeonInternal.deepEquals(lhs.identity, rhs.identity) && ConversationsApiPigeonInternal.deepEquals(lhs.dateCreatedMillis, rhs.dateCreatedMillis) && ConversationsApiPigeonInternal.deepEquals(lhs.lastReadMessageIndex, rhs.lastReadMessageIndex) && ConversationsApiPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ParticipantData")
    ConversationsApiPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: identity, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: dateCreatedMillis, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: lastReadMessageIndex, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
  }

  public var description: String {
    return "ParticipantData(sid: \(String(describing: sid)), identity: \(String(describing: identity)), dateCreatedMillis: \(String(describing: dateCreatedMillis)), lastReadMessageIndex: \(String(describing: lastReadMessageIndex)), attributesJson: \(String(describing: attributesJson)))"
  }
}

/// Everything native code reports on its own (api-design §7).
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol PlatformEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionStateEvent: PlatformEvent {
  var state: PlatformConnectionState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionStateEvent? {
    let state = pigeonVar_list[0] as! PlatformConnectionState

    return ConnectionStateEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: ConnectionStateEvent, rhs: ConnectionStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionStateEvent")
    ConversationsApiPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "ConnectionStateEvent(state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SyncStatusEvent: PlatformEvent {
  var status: PlatformSyncStatus


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncStatusEvent? {
    let status = pigeonVar_list[0] as! PlatformSyncStatus

    return SyncStatusEvent(
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      status
    ]
  }
  static func == (lhs: SyncStatusEvent, rhs: SyncStatusEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SyncStatusEvent")
    ConversationsApiPigeonInternal.deepHash(value: status, hasher: &hasher)
  }

  public var description: String {
    return "SyncStatusEvent(status: \(String(describing: status)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenEvent: PlatformEvent {
  var type: PlatformTokenEventType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenEvent? {
    let type = pigeonVar_list[0] as! PlatformTokenEventType

    return TokenEvent(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: TokenEvent, rhs: TokenEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TokenEvent")
    ConversationsApiPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "TokenEvent(type: \(String(describing: type)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConversationAddedEvent: PlatformEvent {
  var conversation: ConversationData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConversationAddedEvent? {
    let conversation = pigeonVar_list[0] as! ConversationData

    return ConversationAddedEvent(
      conversation: conversation
    )
  }
  func toList() -> [Any?] {
    return [
      conversation
    ]
  }
  static func == (lhs: ConversationAddedEvent, rhs: ConversationAddedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.conversation, rhs.conversation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConversationAddedEvent")
    ConversationsApiPigeonInternal.deepHash(value: conversation, hasher: &hasher)
  }

  public var description: String {
    return "ConversationAddedEvent(conversation: \(String(describing: conversation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageAddedEvent: PlatformEvent {
  var message: MessageData
  var conversation: ConversationData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageAddedEvent? {
    let message = pigeonVar_list[0] as! MessageData
    let conversation = pigeonVar_list[1] as! ConversationData

    return MessageAddedEvent(
      message: message,
      conversation: conversation
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      conversation,
    ]
  }
  static func == (lhs: MessageAddedEvent, rhs: MessageAddedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.message, rhs.message) && ConversationsApiPigeonInternal.deepEquals(lhs.conversation, rhs.conversation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MessageAddedEvent")
    ConversationsApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: conversation, hasher: &hasher)
  }

  public var description: String {
    return "MessageAddedEvent(message: \(String(describing: message)), conversation: \(String(describing: conversation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageUpdatedEvent: PlatformEvent {
  var message: MessageData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageUpdatedEvent? {
    let message = pigeonVar_list[0] as! MessageData

    return MessageUpdatedEvent(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: MessageUpdatedEvent, rhs: MessageUpdatedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MessageUpdatedEvent")
    ConversationsApiPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "MessageUpdatedEvent(message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TypingEvent: PlatformEvent {
  var conversationSid: String
  var participant: ParticipantData
  var started: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TypingEvent? {
    let conversationSid = pigeonVar_list[0] as! String
    let participant = pigeonVar_list[1] as! ParticipantData
    let started = pigeonVar_list[2] as! Bool

    return TypingEvent(
      conversationSid: conversationSid,
      participant: participant,
      started: started
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      participant,
      started,
    ]
  }
  static func == (lhs: TypingEvent, rhs: TypingEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsApiPigeonInternal.deepEquals(lhs.participant, rhs.participant) && ConversationsApiPigeonInternal.deepEquals(lhs.started, rhs.started)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TypingEvent")
    ConversationsApiPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: participant, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: started, hasher: &hasher)
  }

  public var description: String {
    return "TypingEvent(conversationSid: \(String(describing: conversationSid)), participant: \(String(describing: participant)), started: \(String(describing: started)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UploadProgressEvent: PlatformEvent {
  var uploadId: String
  var bytesSent: Int64
  var totalBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UploadProgressEvent? {
    let uploadId = pigeonVar_list[0] as! String
    let bytesSent = pigeonVar_list[1] as! Int64
    let totalBytes = pigeonVar_list[2] as! Int64

    return UploadProgressEvent(
      uploadId: uploadId,
      bytesSent: bytesSent,
      totalBytes: totalBytes
    )
  }
  func toList() -> [Any?] {
    return [
      uploadId,
      bytesSent,
      totalBytes,
    ]
  }
  static func == (lhs: UploadProgressEvent, rhs: UploadProgressEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.uploadId, rhs.uploadId) && ConversationsApiPigeonInternal.deepEquals(lhs.bytesSent, rhs.bytesSent) && ConversationsApiPigeonInternal.deepEquals(lhs.totalBytes, rhs.totalBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UploadProgressEvent")
    ConversationsApiPigeonInternal.deepHash(value: uploadId, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: bytesSent, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: totalBytes, hasher: &hasher)
  }

  public var description: String {
    return "UploadProgressEvent(uploadId: \(String(describing: uploadId)), bytesSent: \(String(describing: bytesSent)), totalBytes: \(String(describing: totalBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientErrorEvent: PlatformEvent {
  var code: String
  var message: String
  var twilioCode: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientErrorEvent? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let twilioCode: Int64? = nilOrValue(pigeonVar_list[2])

    return ClientErrorEvent(
      code: code,
      message: message,
      twilioCode: twilioCode
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      twilioCode,
    ]
  }
  static func == (lhs: ClientErrorEvent, rhs: ClientErrorEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsApiPigeonInternal.deepEquals(lhs.code, rhs.code) && ConversationsApiPigeonInternal.deepEquals(lhs.message, rhs.message) && ConversationsApiPigeonInternal.deepEquals(lhs.twilioCode, rhs.twilioCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientErrorEvent")
    ConversationsApiPigeonInternal.deepHash(value: code, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    ConversationsApiPigeonInternal.deepHash(value: twilioCode, hasher: &hasher)
  }

  public var description: String {
    return "ClientErrorEvent(code: \(String(describing: code)), message: \(String(describing: message)), twilioCode: \(String(describing: twilioCode)))"
  }
}

private class ConversationsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformSyncStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformLogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformConversationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMediaCategory(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPushTokenType(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformTokenEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return ClientData.fromList(self.readValue() as! [Any?])
    case 137:
      return ConversationData.fromList(self.readValue() as! [Any?])
    case 138:
      return MediaData.fromList(self.readValue() as! [Any?])
    case 139:
      return MessageData.fromList(self.readValue() as! [Any?])
    case 140:
      return ParticipantData.fromList(self.readValue() as! [Any?])
    case 141:
      return ConnectionStateEvent.fromList(self.readValue() as! [Any?])
    case 142:
      return SyncStatusEvent.fromList(self.readValue() as! [Any?])
    case 143:
      return TokenEvent.fromList(self.readValue() as! [Any?])
    case 144:
      return ConversationAddedEvent.fromList(self.readValue() as! [Any?])
    case 145:
      return MessageAddedEvent.fromList(self.readValue() as! [Any?])
    case 146:
      return MessageUpdatedEvent.fromList(self.readValue() as! [Any?])
    case 147:
      return TypingEvent.fromList(self.readValue() as! [Any?])
    case 148:
      return UploadProgressEvent.fromList(self.readValue() as! [Any?])
    case 149:
      return ClientErrorEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ConversationsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformConnectionState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformSyncStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformLogLevel {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformConversationStatus {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMediaCategory {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformPushTokenType {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformTokenEventType {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClientData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ConversationData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? MediaData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? MessageData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ParticipantData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionStateEvent {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? SyncStatusEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? TokenEvent {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? ConversationAddedEvent {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? MessageAddedEvent {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? MessageUpdatedEvent {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? TypingEvent {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? UploadProgressEvent {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? ClientErrorEvent {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ConversationsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ConversationsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ConversationsApiPigeonCodecWriter(data: data)
  }
}

class ConversationsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ConversationsApiPigeonCodec(readerWriter: ConversationsApiPigeonCodecReaderWriter())
}

var conversationsApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: ConversationsApiPigeonCodecReaderWriter());


/// Calls from Dart into native code. Everything that waits on Twilio is @async.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ConversationsHostApi {
  func connect(token: String, region: String) async throws -> ClientData
  func updateToken(token: String) async throws
  func shutdown() async throws
  func setLogLevel(level: PlatformLogLevel) throws
  func myConversations() async throws -> [ConversationData]
  func getConversation(sidOrUniqueName: String) async throws -> ConversationData
  func createConversation(uniqueName: String?, friendlyName: String?, attributesJson: String?) async throws -> ConversationData
  func join(conversationSid: String) async throws -> ConversationData
  func getParticipantByIdentity(conversationSid: String, identity: String) async throws -> ParticipantData?
  func getMessagesCount(conversationSid: String) async throws -> Int64
  func getMessagesBefore(conversationSid: String, index: Int64, count: Int64) async throws -> [MessageData]
  func getLastMessages(conversationSid: String, count: Int64) async throws -> [MessageData]
  func getUnreadMessagesCount(conversationSid: String) async throws -> Int64?
  func setLastReadMessageIndex(conversationSid: String, index: Int64) async throws -> Int64?
  func sendText(conversationSid: String, body: String) async throws -> MessageData
  /// Progress arrives as [UploadProgressEvent]s carrying [uploadId].
  func sendMedia(conversationSid: String, uploadId: String, filePath: String, contentType: String, filename: String?) async throws -> MessageData
  func typing(conversationSid: String) async throws
  func getMediaTemporaryUrl(conversationSid: String, messageIndex: Int64, mediaSid: String) async throws -> String
  func registerPushToken(type: PlatformPushTokenType, token: String) async throws
  func unregisterPushToken(type: PlatformPushTokenType, token: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ConversationsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ConversationsApiPigeonCodec.shared }
  /// Sets up an instance of `ConversationsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ConversationsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        let regionArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.connect(token: tokenArg, region: regionArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let updateTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.updateToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.updateToken(token: tokenArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateTokenChannel.setMessageHandler(nil)
    }
    let shutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.shutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shutdownChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.shutdown()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      shutdownChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! PlatformLogLevel
        do {
          try api.setLogLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
    let myConversationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.myConversations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      myConversationsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.myConversations()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      myConversationsChannel.setMessageHandler(nil)
    }
    let getConversationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getConversation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConversationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sidOrUniqueNameArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getConversation(sidOrUniqueName: sidOrUniqueNameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConversationChannel.setMessageHandler(nil)
    }
    let createConversationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.createConversation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createConversationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uniqueNameArg: String? = nilOrValue(args[0])
        let friendlyNameArg: String? = nilOrValue(args[1])
        let attributesJsonArg: String? = nilOrValue(args[2])
        Task { @MainActor in
          do {
            let result = try await api.createConversation(uniqueName: uniqueNameArg, friendlyName: friendlyNameArg, attributesJson: attributesJsonArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createConversationChannel.setMessageHandler(nil)
    }
    let joinChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.join\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.join(conversationSid: conversationSidArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      joinChannel.setMessageHandler(nil)
    }
    let getParticipantByIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getParticipantByIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getParticipantByIdentityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let identityArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.getParticipantByIdentity(conversationSid: conversationSidArg, identity: identityArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getParticipantByIdentityChannel.setMessageHandler(nil)
    }
    let getMessagesCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMessagesCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMessagesCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getMessagesCount(conversationSid: conversationSidArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMessagesCountChannel.setMessageHandler(nil)
    }
    let getMessagesBeforeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMessagesBefore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMessagesBeforeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let indexArg = args[1] as! Int64
        let countArg = args[2] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.getMessagesBefore(conversationSid: conversationSidArg, index: indexArg, count: countArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMessagesBeforeChannel.setMessageHandler(nil)
    }
    let getLastMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getLastMessages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLastMessagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let countArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.getLastMessages(conversationSid: conversationSidArg, count: countArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getLastMessagesChannel.setMessageHandler(nil)
    }
    let getUnreadMessagesCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getUnreadMessagesCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUnreadMessagesCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getUnreadMessagesCount(conversationSid: conversationSidArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUnreadMessagesCountChannel.setMessageHandler(nil)
    }
    let setLastReadMessageIndexChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.setLastReadMessageIndex\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLastReadMessageIndexChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let indexArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.setLastReadMessageIndex(conversationSid: conversationSidArg, index: indexArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLastReadMessageIndexChannel.setMessageHandler(nil)
    }
    let sendTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.sendText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let bodyArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.sendText(conversationSid: conversationSidArg, body: bodyArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTextChannel.setMessageHandler(nil)
    }
    /// Progress arrives as [UploadProgressEvent]s carrying [uploadId].
    let sendMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.sendMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let uploadIdArg = args[1] as! String
        let filePathArg = args[2] as! String
        let contentTypeArg = args[3] as! String
        let filenameArg: String? = nilOrValue(args[4])
        Task { @MainActor in
          do {
            let result = try await api.sendMedia(conversationSid: conversationSidArg, uploadId: uploadIdArg, filePath: filePathArg, contentType: contentTypeArg, filename: filenameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMediaChannel.setMessageHandler(nil)
    }
    let typingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.typing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      typingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.typing(conversationSid: conversationSidArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      typingChannel.setMessageHandler(nil)
    }
    let getMediaTemporaryUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMediaTemporaryUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaTemporaryUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conversationSidArg = args[0] as! String
        let messageIndexArg = args[1] as! Int64
        let mediaSidArg = args[2] as! String
        Task { @MainActor in
          do {
            let result = try await api.getMediaTemporaryUrl(conversationSid: conversationSidArg, messageIndex: messageIndexArg, mediaSid: mediaSidArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaTemporaryUrlChannel.setMessageHandler(nil)
    }
    let registerPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.registerPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! PlatformPushTokenType
        let tokenArg = args[1] as! String
        Task { @MainActor in
          do {
            try await api.registerPushToken(type: typeArg, token: tokenArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPushTokenChannel.setMessageHandler(nil)
    }
    let unregisterPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.unregisterPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! PlatformPushTokenType
        let tokenArg = args[1] as! String
        Task { @MainActor in
          do {
            try await api.unregisterPushToken(type: typeArg, token: tokenArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      unregisterPushTokenChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class EventsStreamHandler: PigeonEventChannelWrapper<PlatformEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsEventApi.events"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PlatformEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: conversationsApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
