// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.identity_solutions.twilio_conversations

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ConversationsApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlatformConnectionState(val raw: Int) {
  UNKNOWN(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTED(3),
  DENIED(4),
  ERROR(5),
  FATAL_ERROR(6);

  companion object {
    fun ofRaw(raw: Int): PlatformConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformSyncStatus(val raw: Int) {
  STARTED(0),
  CONVERSATIONS_LIST_COMPLETED(1),
  COMPLETED(2),
  FAILED(3);

  companion object {
    fun ofRaw(raw: Int): PlatformSyncStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformLogLevel(val raw: Int) {
  SILENT(0),
  FATAL(1),
  ERROR(2),
  WARNING(3),
  INFO(4),
  DEBUG(5),
  TRACE(6);

  companion object {
    fun ofRaw(raw: Int): PlatformLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformConversationStatus(val raw: Int) {
  JOINED(0),
  NOT_PARTICIPATING(1);

  companion object {
    fun ofRaw(raw: Int): PlatformConversationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformMediaCategory(val raw: Int) {
  MEDIA(0),
  BODY(1),
  HISTORY(2);

  companion object {
    fun ofRaw(raw: Int): PlatformMediaCategory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformPushTokenType(val raw: Int) {
  APNS(0),
  FCM(1);

  companion object {
    fun ofRaw(raw: Int): PlatformPushTokenType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformTokenEventType(val raw: Int) {
  ABOUT_TO_EXPIRE(0),
  EXPIRED(1);

  companion object {
    fun ofRaw(raw: Int): PlatformTokenEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ClientData (
  val myIdentity: String,
  val connectionState: PlatformConnectionState,
  val syncStatus: PlatformSyncStatus? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClientData {
      val myIdentity = pigeonVar_list[0] as String
      val connectionState = pigeonVar_list[1] as PlatformConnectionState
      val syncStatus = pigeonVar_list[2] as PlatformSyncStatus?
      return ClientData(myIdentity, connectionState, syncStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      myIdentity,
      connectionState,
      syncStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ClientData
    return ConversationsApiPigeonUtils.deepEquals(this.myIdentity, other.myIdentity) && ConversationsApiPigeonUtils.deepEquals(this.connectionState, other.connectionState) && ConversationsApiPigeonUtils.deepEquals(this.syncStatus, other.syncStatus)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.myIdentity)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.connectionState)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.syncStatus)
    return result
  }
  override fun toString(): String {
    return "ClientData(myIdentity=$myIdentity, connectionState=$connectionState, syncStatus=$syncStatus)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationData (
  val sid: String,
  val status: PlatformConversationStatus,
  val uniqueName: String? = null,
  val friendlyName: String? = null,
  val attributesJson: String? = null,
  val lastMessageIndex: Long? = null,
  val lastMessageDateMillis: Long? = null,
  val lastReadMessageIndex: Long? = null,
  val dateCreatedMillis: Long? = null,
  val createdBy: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationData {
      val sid = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as PlatformConversationStatus
      val uniqueName = pigeonVar_list[2] as String?
      val friendlyName = pigeonVar_list[3] as String?
      val attributesJson = pigeonVar_list[4] as String?
      val lastMessageIndex = pigeonVar_list[5] as Long?
      val lastMessageDateMillis = pigeonVar_list[6] as Long?
      val lastReadMessageIndex = pigeonVar_list[7] as Long?
      val dateCreatedMillis = pigeonVar_list[8] as Long?
      val createdBy = pigeonVar_list[9] as String?
      return ConversationData(sid, status, uniqueName, friendlyName, attributesJson, lastMessageIndex, lastMessageDateMillis, lastReadMessageIndex, dateCreatedMillis, createdBy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      status,
      uniqueName,
      friendlyName,
      attributesJson,
      lastMessageIndex,
      lastMessageDateMillis,
      lastReadMessageIndex,
      dateCreatedMillis,
      createdBy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConversationData
    return ConversationsApiPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsApiPigeonUtils.deepEquals(this.status, other.status) && ConversationsApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && ConversationsApiPigeonUtils.deepEquals(this.friendlyName, other.friendlyName) && ConversationsApiPigeonUtils.deepEquals(this.attributesJson, other.attributesJson) && ConversationsApiPigeonUtils.deepEquals(this.lastMessageIndex, other.lastMessageIndex) && ConversationsApiPigeonUtils.deepEquals(this.lastMessageDateMillis, other.lastMessageDateMillis) && ConversationsApiPigeonUtils.deepEquals(this.lastReadMessageIndex, other.lastReadMessageIndex) && ConversationsApiPigeonUtils.deepEquals(this.dateCreatedMillis, other.dateCreatedMillis) && ConversationsApiPigeonUtils.deepEquals(this.createdBy, other.createdBy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.status)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.friendlyName)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.attributesJson)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.lastMessageIndex)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.lastMessageDateMillis)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.lastReadMessageIndex)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.dateCreatedMillis)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.createdBy)
    return result
  }
  override fun toString(): String {
    return "ConversationData(sid=$sid, status=$status, uniqueName=$uniqueName, friendlyName=$friendlyName, attributesJson=$attributesJson, lastMessageIndex=$lastMessageIndex, lastMessageDateMillis=$lastMessageDateMillis, lastReadMessageIndex=$lastReadMessageIndex, dateCreatedMillis=$dateCreatedMillis, createdBy=$createdBy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaData (
  val sid: String,
  val category: PlatformMediaCategory,
  val contentType: String,
  val size: Long,
  val filename: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaData {
      val sid = pigeonVar_list[0] as String
      val category = pigeonVar_list[1] as PlatformMediaCategory
      val contentType = pigeonVar_list[2] as String
      val size = pigeonVar_list[3] as Long
      val filename = pigeonVar_list[4] as String?
      return MediaData(sid, category, contentType, size, filename)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      category,
      contentType,
      size,
      filename,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaData
    return ConversationsApiPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsApiPigeonUtils.deepEquals(this.category, other.category) && ConversationsApiPigeonUtils.deepEquals(this.contentType, other.contentType) && ConversationsApiPigeonUtils.deepEquals(this.size, other.size) && ConversationsApiPigeonUtils.deepEquals(this.filename, other.filename)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.category)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.contentType)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.size)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.filename)
    return result
  }
  override fun toString(): String {
    return "MediaData(sid=$sid, category=$category, contentType=$contentType, size=$size, filename=$filename)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageData (
  val conversationSid: String,
  val sid: String,
  val index: Long,
  val media: List<MediaData>,
  val author: String? = null,
  val body: String? = null,
  val dateCreatedMillis: Long? = null,
  val attributesJson: String? = null,
  val participantSid: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageData {
      val conversationSid = pigeonVar_list[0] as String
      val sid = pigeonVar_list[1] as String
      val index = pigeonVar_list[2] as Long
      val media = pigeonVar_list[3] as List<MediaData>
      val author = pigeonVar_list[4] as String?
      val body = pigeonVar_list[5] as String?
      val dateCreatedMillis = pigeonVar_list[6] as Long?
      val attributesJson = pigeonVar_list[7] as String?
      val participantSid = pigeonVar_list[8] as String?
      return MessageData(conversationSid, sid, index, media, author, body, dateCreatedMillis, attributesJson, participantSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      sid,
      index,
      media,
      author,
      body,
      dateCreatedMillis,
      attributesJson,
      participantSid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessageData
    return ConversationsApiPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsApiPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsApiPigeonUtils.deepEquals(this.index, other.index) && ConversationsApiPigeonUtils.deepEquals(this.media, other.media) && ConversationsApiPigeonUtils.deepEquals(this.author, other.author) && ConversationsApiPigeonUtils.deepEquals(this.body, other.body) && ConversationsApiPigeonUtils.deepEquals(this.dateCreatedMillis, other.dateCreatedMillis) && ConversationsApiPigeonUtils.deepEquals(this.attributesJson, other.attributesJson) && ConversationsApiPigeonUtils.deepEquals(this.participantSid, other.participantSid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.index)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.media)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.author)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.body)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.dateCreatedMillis)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.attributesJson)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.participantSid)
    return result
  }
  override fun toString(): String {
    return "MessageData(conversationSid=$conversationSid, sid=$sid, index=$index, media=$media, author=$author, body=$body, dateCreatedMillis=$dateCreatedMillis, attributesJson=$attributesJson, participantSid=$participantSid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ParticipantData (
  val sid: String,
  val identity: String? = null,
  val dateCreatedMillis: Long? = null,
  val lastReadMessageIndex: Long? = null,
  val attributesJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ParticipantData {
      val sid = pigeonVar_list[0] as String
      val identity = pigeonVar_list[1] as String?
      val dateCreatedMillis = pigeonVar_list[2] as Long?
      val lastReadMessageIndex = pigeonVar_list[3] as Long?
      val attributesJson = pigeonVar_list[4] as String?
      return ParticipantData(sid, identity, dateCreatedMillis, lastReadMessageIndex, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      identity,
      dateCreatedMillis,
      lastReadMessageIndex,
      attributesJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ParticipantData
    return ConversationsApiPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsApiPigeonUtils.deepEquals(this.identity, other.identity) && ConversationsApiPigeonUtils.deepEquals(this.dateCreatedMillis, other.dateCreatedMillis) && ConversationsApiPigeonUtils.deepEquals(this.lastReadMessageIndex, other.lastReadMessageIndex) && ConversationsApiPigeonUtils.deepEquals(this.attributesJson, other.attributesJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.identity)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.dateCreatedMillis)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.lastReadMessageIndex)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.attributesJson)
    return result
  }
  override fun toString(): String {
    return "ParticipantData(sid=$sid, identity=$identity, dateCreatedMillis=$dateCreatedMillis, lastReadMessageIndex=$lastReadMessageIndex, attributesJson=$attributesJson)"
  }
}

/**
 * Everything native code reports on its own (api-design §7).
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class PlatformEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionStateEvent (
  val state: PlatformConnectionState
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionStateEvent {
      val state = pigeonVar_list[0] as PlatformConnectionState
      return ConnectionStateEvent(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionStateEvent
    return ConversationsApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "ConnectionStateEvent(state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncStatusEvent (
  val status: PlatformSyncStatus
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncStatusEvent {
      val status = pigeonVar_list[0] as PlatformSyncStatus
      return SyncStatusEvent(status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SyncStatusEvent
    return ConversationsApiPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.status)
    return result
  }
  override fun toString(): String {
    return "SyncStatusEvent(status=$status)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenEvent (
  val type: PlatformTokenEventType
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenEvent {
      val type = pigeonVar_list[0] as PlatformTokenEventType
      return TokenEvent(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TokenEvent
    return ConversationsApiPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.type)
    return result
  }
  override fun toString(): String {
    return "TokenEvent(type=$type)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationAddedEvent (
  val conversation: ConversationData
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationAddedEvent {
      val conversation = pigeonVar_list[0] as ConversationData
      return ConversationAddedEvent(conversation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConversationAddedEvent
    return ConversationsApiPigeonUtils.deepEquals(this.conversation, other.conversation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.conversation)
    return result
  }
  override fun toString(): String {
    return "ConversationAddedEvent(conversation=$conversation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageAddedEvent (
  val message: MessageData,
  val conversation: ConversationData
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageAddedEvent {
      val message = pigeonVar_list[0] as MessageData
      val conversation = pigeonVar_list[1] as ConversationData
      return MessageAddedEvent(message, conversation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
      conversation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessageAddedEvent
    return ConversationsApiPigeonUtils.deepEquals(this.message, other.message) && ConversationsApiPigeonUtils.deepEquals(this.conversation, other.conversation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.message)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.conversation)
    return result
  }
  override fun toString(): String {
    return "MessageAddedEvent(message=$message, conversation=$conversation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageUpdatedEvent (
  val message: MessageData
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageUpdatedEvent {
      val message = pigeonVar_list[0] as MessageData
      return MessageUpdatedEvent(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessageUpdatedEvent
    return ConversationsApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "MessageUpdatedEvent(message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TypingEvent (
  val conversationSid: String,
  val participant: ParticipantData,
  val started: Boolean
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TypingEvent {
      val conversationSid = pigeonVar_list[0] as String
      val participant = pigeonVar_list[1] as ParticipantData
      val started = pigeonVar_list[2] as Boolean
      return TypingEvent(conversationSid, participant, started)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      participant,
      started,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TypingEvent
    return ConversationsApiPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsApiPigeonUtils.deepEquals(this.participant, other.participant) && ConversationsApiPigeonUtils.deepEquals(this.started, other.started)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.participant)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.started)
    return result
  }
  override fun toString(): String {
    return "TypingEvent(conversationSid=$conversationSid, participant=$participant, started=$started)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UploadProgressEvent (
  val uploadId: String,
  val bytesSent: Long,
  val totalBytes: Long
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UploadProgressEvent {
      val uploadId = pigeonVar_list[0] as String
      val bytesSent = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return UploadProgressEvent(uploadId, bytesSent, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uploadId,
      bytesSent,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UploadProgressEvent
    return ConversationsApiPigeonUtils.deepEquals(this.uploadId, other.uploadId) && ConversationsApiPigeonUtils.deepEquals(this.bytesSent, other.bytesSent) && ConversationsApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.uploadId)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.bytesSent)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.totalBytes)
    return result
  }
  override fun toString(): String {
    return "UploadProgressEvent(uploadId=$uploadId, bytesSent=$bytesSent, totalBytes=$totalBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ClientErrorEvent (
  val code: String,
  val message: String,
  val twilioCode: Long? = null
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClientErrorEvent {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val twilioCode = pigeonVar_list[2] as Long?
      return ClientErrorEvent(code, message, twilioCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      twilioCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ClientErrorEvent
    return ConversationsApiPigeonUtils.deepEquals(this.code, other.code) && ConversationsApiPigeonUtils.deepEquals(this.message, other.message) && ConversationsApiPigeonUtils.deepEquals(this.twilioCode, other.twilioCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.code)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.message)
    result = 31 * result + ConversationsApiPigeonUtils.deepHash(this.twilioCode)
    return result
  }
  override fun toString(): String {
    return "ClientErrorEvent(code=$code, message=$message, twilioCode=$twilioCode)"
  }
}
private open class ConversationsApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformConnectionState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformSyncStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformLogLevel.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformConversationStatus.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformMediaCategory.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformPushTokenType.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformTokenEventType.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClientData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaData.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageData.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ParticipantData.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionStateEvent.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncStatusEvent.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenEvent.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationAddedEvent.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageAddedEvent.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageUpdatedEvent.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TypingEvent.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UploadProgressEvent.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClientErrorEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformConnectionState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformSyncStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformLogLevel -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformConversationStatus -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformMediaCategory -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformPushTokenType -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformTokenEventType -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is ClientData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ConversationData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is MediaData -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MessageData -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is ParticipantData -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ConnectionStateEvent -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is SyncStatusEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is TokenEvent -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is ConversationAddedEvent -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is MessageAddedEvent -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is MessageUpdatedEvent -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is TypingEvent -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is UploadProgressEvent -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is ClientErrorEvent -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val ConversationsApiPigeonMethodCodec = StandardMethodCodec(ConversationsApiPigeonCodec())


/**
 * Calls from Dart into native code. Everything that waits on Twilio is @async.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ConversationsHostApi {
  suspend fun connect(token: String, region: String): ClientData
  suspend fun updateToken(token: String)
  suspend fun shutdown()
  fun setLogLevel(level: PlatformLogLevel)
  suspend fun myConversations(): List<ConversationData>
  suspend fun getConversation(sidOrUniqueName: String): ConversationData
  suspend fun createConversation(uniqueName: String?, friendlyName: String?, attributesJson: String?): ConversationData
  suspend fun join(conversationSid: String): ConversationData
  suspend fun getParticipantByIdentity(conversationSid: String, identity: String): ParticipantData?
  suspend fun getMessagesCount(conversationSid: String): Long
  suspend fun getMessagesBefore(conversationSid: String, index: Long, count: Long): List<MessageData>
  suspend fun getLastMessages(conversationSid: String, count: Long): List<MessageData>
  suspend fun getUnreadMessagesCount(conversationSid: String): Long?
  suspend fun setLastReadMessageIndex(conversationSid: String, index: Long): Long?
  suspend fun sendText(conversationSid: String, body: String): MessageData
  /** Progress arrives as [UploadProgressEvent]s carrying [uploadId]. */
  suspend fun sendMedia(conversationSid: String, uploadId: String, filePath: String, contentType: String, filename: String?): MessageData
  suspend fun typing(conversationSid: String)
  suspend fun getMediaTemporaryUrl(conversationSid: String, messageIndex: Long, mediaSid: String): String
  suspend fun registerPushToken(type: PlatformPushTokenType, token: String)
  suspend fun unregisterPushToken(type: PlatformPushTokenType, token: String)

  companion object {
    /** The codec used by ConversationsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ConversationsApiPigeonCodec()
    }
    /** Sets up an instance of `ConversationsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ConversationsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            val regionArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.connect(tokenArg, regionArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.updateToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.updateToken(tokenArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.shutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.shutdown()
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as PlatformLogLevel
            val wrapped: List<Any?> = try {
              api.setLogLevel(levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              ConversationsApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.myConversations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.myConversations())
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sidOrUniqueNameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getConversation(sidOrUniqueNameArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.createConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uniqueNameArg = args[0] as String?
            val friendlyNameArg = args[1] as String?
            val attributesJsonArg = args[2] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createConversation(uniqueNameArg, friendlyNameArg, attributesJsonArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.join$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.join(conversationSidArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getParticipantByIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val identityArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getParticipantByIdentity(conversationSidArg, identityArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMessagesCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMessagesCount(conversationSidArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMessagesBefore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val indexArg = args[1] as Long
            val countArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMessagesBefore(conversationSidArg, indexArg, countArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getLastMessages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val countArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getLastMessages(conversationSidArg, countArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getUnreadMessagesCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getUnreadMessagesCount(conversationSidArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.setLastReadMessageIndex$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val indexArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.setLastReadMessageIndex(conversationSidArg, indexArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.sendText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val bodyArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendText(conversationSidArg, bodyArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.sendMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val uploadIdArg = args[1] as String
            val filePathArg = args[2] as String
            val contentTypeArg = args[3] as String
            val filenameArg = args[4] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendMedia(conversationSidArg, uploadIdArg, filePathArg, contentTypeArg, filenameArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.typing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.typing(conversationSidArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.getMediaTemporaryUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val conversationSidArg = args[0] as String
            val messageIndexArg = args[1] as Long
            val mediaSidArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMediaTemporaryUrl(conversationSidArg, messageIndexArg, mediaSidArg))
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.registerPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as PlatformPushTokenType
            val tokenArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.registerPushToken(typeArg, tokenArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsHostApi.unregisterPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as PlatformPushTokenType
            val tokenArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.unregisterPushToken(typeArg, tokenArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class ConversationsApiPigeonStreamHandler<T>(
    val wrapper: ConversationsApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface ConversationsApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class EventsStreamHandler : ConversationsApiPigeonEventChannelWrapper<PlatformEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_twilio_conversations_client.ConversationsEventApi.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = ConversationsApiPigeonStreamHandler<PlatformEvent>(streamHandler)
      EventChannel(messenger, channelName, ConversationsApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from ConversationsApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
